/* Generated by Yosys 0.36+67 (git sha1 1ddb0892c, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(ovf, clk, rst, en);
  reg \$auto$verilog_backend.cc:2189:dump_module$1  = 0;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:34" *)
  wire \$1 ;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:40" *)
  wire [16:0] \$3 ;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:40" *)
  wire [16:0] \$4 ;
  (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:508" *)
  input clk;
  wire clk;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:29" *)
  reg [15:0] count = 16'h0000;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:29" *)
  reg [15:0] \count$next ;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:25" *)
  input en;
  wire en;
  (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:26" *)
  output ovf;
  wire ovf;
  (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:508" *)
  input rst;
  wire rst;
  assign \$1  = count == (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:34" *) 5'h19;
  assign \$4  = count + (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:40" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \count$next  = count;
    (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:36" *)
    casez (en)
      /* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:36" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:37" *)
          casez (ovf)
            /* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:37" */
            1'h1:
                \count$next  = 16'h0000;
            /* src = "/home/bcheng/dev/amahdl/up_counter/up_counter.py:39" */
            default:
                \count$next  = \$4 [15:0];
          endcase
    endcase
    (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:503" *)
    casez (rst)
      1'h1:
          \count$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
