/* Generated by Yosys 0.36+67 (git sha1 1ddb0892c, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(g_led, b_led, clk, rst, r_led);
  reg \$auto$verilog_backend.cc:2189:dump_module$1  = 0;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" *)
  wire \$10 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:78" *)
  wire [8:0] \$12 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:78" *)
  wire [8:0] \$13 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:79" *)
  wire [8:0] \$15 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:79" *)
  wire [8:0] \$16 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" *)
  wire \$18 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:86" *)
  wire [8:0] \$20 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:86" *)
  wire [8:0] \$21 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:87" *)
  wire [8:0] \$23 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:87" *)
  wire [8:0] \$24 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" *)
  wire \$26 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:94" *)
  wire [8:0] \$28 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:94" *)
  wire [8:0] \$29 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:95" *)
  wire [8:0] \$31 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:95" *)
  wire [8:0] \$32 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" *)
  wire \$34 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:68" *)
  wire [8:0] \$36 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:68" *)
  wire [8:0] \$37 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" *)
  wire \$39 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:40" *)
  wire \$4 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" *)
  wire \$41 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" *)
  wire \$43 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" *)
  wire \$45 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:45" *)
  wire \$6 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:50" *)
  wire \$8 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:21" *)
  input b_led;
  wire b_led;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:21" *)
  wire \b_led$3 ;
  (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_ir.py:509" *)
  input clk;
  wire clk;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:29" *)
  reg [7:0] duty = 8'h00;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:29" *)
  reg [7:0] \duty$next ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:57" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:57" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:20" *)
  input g_led;
  wire g_led;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:20" *)
  wire \g_led$2 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:19" *)
  input r_led;
  wire r_led;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:19" *)
  wire \r_led$1 ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:28" *)
  reg [23:0] rgb_count = 24'h000000;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:28" *)
  reg [23:0] \rgb_count$next ;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:27" *)
  reg [2:0] rgb_led = 3'h0;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:27" *)
  reg [2:0] \rgb_led$next ;
  (* enum_base_type = "ColorPhase" *)
  (* enum_value_000 = "RED_GREEN" *)
  (* enum_value_001 = "GREEN_BLUE" *)
  (* enum_value_010 = "BLUE_RED" *)
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:30" *)
  reg [2:0] rgb_phase = 3'h0;
  (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:30" *)
  reg [2:0] \rgb_phase$next ;
  (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_ir.py:509" *)
  input rst;
  wire rst;
  assign \$10  = rgb_count[7:0] > (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" *) 1'h0;
  assign \$13  = rgb_count[7:0] - (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:78" *) 1'h1;
  assign \$16  = rgb_count[15:8] + (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:79" *) 1'h1;
  assign \$18  = rgb_count[15:8] > (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" *) 1'h0;
  assign \$21  = rgb_count[15:8] - (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:86" *) 1'h1;
  assign \$24  = rgb_count[23:16] + (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:87" *) 1'h1;
  assign \$26  = rgb_count[23:16] > (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" *) 1'h0;
  assign \$29  = rgb_count[23:16] - (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:94" *) 1'h1;
  assign \$32  = rgb_count[7:0] + (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:95" *) 1'h1;
  assign \$34  = duty < (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" *) 8'hff;
  assign \$37  = duty + (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:68" *) 1'h1;
  assign \$39  = duty < (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" *) 8'hff;
  assign \$41  = rgb_count[7:0] > (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" *) 1'h0;
  assign \$43  = rgb_count[15:8] > (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" *) 1'h0;
  assign \$45  = rgb_count[23:16] > (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" *) 1'h0;
  always @(posedge clk)
    rgb_led <= \rgb_led$next ;
  always @(posedge clk)
    rgb_count <= \rgb_count$next ;
  always @(posedge clk)
    duty <= \duty$next ;
  assign \$4  = duty < (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:40" *) rgb_count[7:0];
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    rgb_phase <= \rgb_phase$next ;
  assign \$6  = duty < (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:45" *) rgb_count[15:8];
  assign \$8  = duty < (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:50" *) rgb_count[23:16];
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:40" *)
    casez (\$4 )
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:40" */
      1'h1:
          \rgb_led$next [0] = 1'h1;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:42" */
      default:
          \rgb_led$next [0] = 1'h0;
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:45" *)
    casez (\$6 )
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:45" */
      1'h1:
          \rgb_led$next [1] = 1'h1;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:47" */
      default:
          \rgb_led$next [1] = 1'h0;
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:50" *)
    casez (\$8 )
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:50" */
      1'h1:
          \rgb_led$next [2] = 1'h1;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:52" */
      default:
          \rgb_led$next [2] = 1'h0;
    endcase
    (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_xfrm.py:534" *)
    casez (rst)
      1'h1:
          \rgb_led$next  = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rgb_count$next  = rgb_count;
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:57" *)
    casez (fsm_state)
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:58" */
      /* \amaranth.decoding  = "INIT/0" */
      2'h0:
        begin
          \rgb_count$next [7:0] = 8'hff;
          \rgb_count$next [15:8] = 8'h00;
          \rgb_count$next [23:16] = 8'h00;
        end
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:66" */
      /* \amaranth.decoding  = "INCR_DUTY/1" */
      2'h1:
          /* empty */;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:73" */
      /* \amaranth.decoding  = "SHIFT_COLOR/2" */
      2'h2:
          (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:74" *)
          casez (rgb_phase)
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:75" */
            /* \amaranth.decoding  = "RED_GREEN/0" */
            3'h0:
                (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" *)
                casez (\$10 )
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" */
                  1'h1:
                    begin
                      \rgb_count$next [7:0] = \$13 [7:0];
                      \rgb_count$next [15:8] = \$16 [7:0];
                    end
                endcase
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:83" */
            /* \amaranth.decoding  = "GREEN_BLUE/1" */
            3'h1:
                (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" *)
                casez (\$18 )
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" */
                  1'h1:
                    begin
                      \rgb_count$next [15:8] = \$21 [7:0];
                      \rgb_count$next [23:16] = \$24 [7:0];
                    end
                endcase
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:91" */
            /* \amaranth.decoding  = "BLUE_RED/2" */
            3'h2:
                (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" *)
                casez (\$26 )
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" */
                  1'h1:
                    begin
                      \rgb_count$next [23:16] = \$29 [7:0];
                      \rgb_count$next [7:0] = \$32 [7:0];
                    end
                endcase
          endcase
    endcase
    (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_xfrm.py:534" *)
    casez (rst)
      1'h1:
          \rgb_count$next  = 24'h000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \duty$next  = duty;
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:57" *)
    casez (fsm_state)
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:58" */
      /* \amaranth.decoding  = "INIT/0" */
      2'h0:
          \duty$next  = 8'h00;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:66" */
      /* \amaranth.decoding  = "INCR_DUTY/1" */
      2'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" *)
          casez (\$34 )
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" */
            1'h1:
                \duty$next  = \$37 [7:0];
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:70" */
            default:
                \duty$next  = 8'h00;
          endcase
    endcase
    (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_xfrm.py:534" *)
    casez (rst)
      1'h1:
          \duty$next  = 8'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:57" *)
    casez (fsm_state)
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:58" */
      /* \amaranth.decoding  = "INIT/0" */
      2'h0:
          \fsm_state$next  = 2'h1;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:66" */
      /* \amaranth.decoding  = "INCR_DUTY/1" */
      2'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" *)
          casez (\$39 )
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:67" */
            1'h1:
                \fsm_state$next  = 2'h1;
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:70" */
            default:
                \fsm_state$next  = 2'h2;
          endcase
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:73" */
      /* \amaranth.decoding  = "SHIFT_COLOR/2" */
      2'h2:
          \fsm_state$next  = 2'h1;
    endcase
    (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_xfrm.py:534" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \rgb_phase$next  = rgb_phase;
    (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:57" *)
    casez (fsm_state)
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:58" */
      /* \amaranth.decoding  = "INIT/0" */
      2'h0:
          /* empty */;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:66" */
      /* \amaranth.decoding  = "INCR_DUTY/1" */
      2'h1:
          /* empty */;
      /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:73" */
      /* \amaranth.decoding  = "SHIFT_COLOR/2" */
      2'h2:
          (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:74" *)
          casez (rgb_phase)
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:75" */
            /* \amaranth.decoding  = "RED_GREEN/0" */
            3'h0:
                (* full_case = 32'd1 *)
                (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" *)
                casez (\$41 )
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:76" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:81" */
                  default:
                      \rgb_phase$next  = 3'h1;
                endcase
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:83" */
            /* \amaranth.decoding  = "GREEN_BLUE/1" */
            3'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" *)
                casez (\$43 )
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:84" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:89" */
                  default:
                      \rgb_phase$next  = 3'h2;
                endcase
            /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:91" */
            /* \amaranth.decoding  = "BLUE_RED/2" */
            3'h2:
                (* full_case = 32'd1 *)
                (* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" *)
                casez (\$45 )
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:92" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/bcheng/dev/amahdl/color_cycle/color_cycle.py:97" */
                  default:
                      \rgb_phase$next  = 3'h0;
                endcase
          endcase
    endcase
    (* src = "/home/bcheng/.local/lib/python3.10/site-packages/amaranth/hdl/_xfrm.py:534" *)
    casez (rst)
      1'h1:
          \rgb_phase$next  = 3'h0;
    endcase
  end
  assign \$12  = \$13 ;
  assign \$15  = \$16 ;
  assign \$20  = \$21 ;
  assign \$23  = \$24 ;
  assign \$28  = \$29 ;
  assign \$31  = \$32 ;
  assign \$36  = \$37 ;
  assign \b_led$3  = rgb_led[2];
  assign \g_led$2  = rgb_led[1];
  assign \r_led$1  = rgb_led[0];
endmodule
